---
- hosts: localhost
  connection: local
  tasks:
    - name: create a resource
      azure_rm_resourcegorup:
        name: table3rmdevopsrg
        location: francecentral
        tags:
          testing: testing
          delete: never

