- name: Create  VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: &rg table3-rm-rg-l02
      location: &loc francecentral
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: *rg
      name: &vnet table3-rm-vnet-l02
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: *rg
      name: &subnet table3-rm-subnet-l02
      address_prefix: "10.0.1.0/24"
      virtual_network: *vnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: *rg
      allocation_method: Static
      name: &pubip table3-rm-pubip-l02
    register: output_ip_address
  - name: Output public IP 
    debug:
      msg: "Public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: *rg
      name: &sg table3-rm-sg-l02
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: *rg
      name: &nic table3-rm-nic-l02
      virtual_network: *vnet
      subnet: *subnet
      public_ip_name: *pubip
      security_group: *sg
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: *rg
      name: &vm table3-rm-vm-l02
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ lookup('file','/home/azureops/.ssh/id_rsa.pub')}}"
      network_interfaces: *nic
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04-lst'
        version: latest
