- name: Create  VM
  hosts: localhost
  connection: local
  vars_files:
    - vars.yml
  tasks:
    - include_tasks: resource_group.yml
      loop:
        - group_name: "{{ group_name }}"
          location: francecentral
      loop_control:
        loop_var: rg
    - include_tasks: network.yml
      loop:
        - group_name: "{{ group_name }}"
          vnet_name: "{{ vnet }}"
          vnet_cidr: 10.0.0.0/16
          snet_name: "{{ subnet }}"
          snet_cidr: 10.0.10.0/24
          security_group: "{{ security_group }}" 
      loop_control:
        loop_var: net
    - include_tasks: vm.yml
      loop:
        - name: "{{ prefix }}vm1"
          tags:
            machine_role: nginx
            owner: robert
        - name: "{{ prefix }}vm2"
          tags:
            machine_role: appache
            owner: robert
        - name: "{{ prefix }}vm3"
          tags:
            machine_role: appache
            owner: robert
      loop_control:
        loop_var: vm
