- name: Create  VM
  hosts: localhost
  connection: local
  vars_files:
    - vars.yml
  tasks:
    - include_tasks: "{{ playbook_dir }}/../lib/resource_group.yml"
      loop:
        - group_name: "{{ group_name }}"
          location: francecentral
      loop_control:
        loop_var: rg
    - include_tasks: "{{ playbook_dir }}/../lib/network.yml"
      loop:
        - group_name: "{{ group_name }}"
          vnet_name: "{{ vnet }}"
          vnet_cidr: 10.0.0.0/16
          snet_name: "{{ subnet }}"
          snet_cidr: 10.0.10.0/24
      loop_contorl:
        loop_var: net
    - include_tasks: vm.yml
      loop:
        - name: 'vm-one'
          tags:
            machine_role: nginx
            owner: robert
        - name: 'vm-two'
          tags:
            machine_role: appache
            owner: robert
      loop_control:
        loop_var: vm
