- hosts: localhost
  connection: local
  vars:
    rg: table3-rm-resource-webapp
    wa: table3-rm-myApp-webapp
    wa_plan: table3-rm-waplan-webapp
    location: francecentral
  tasks:
    - name: create rg
      azure_rm_resourcegroup:
        name: "{{ rg }}"
        location: "{{ location }}"
    - name: create app svc
      azure_rm_webapp:
        resource_group: "{{ rg }}"
        name: "{{ wa }}"
        plan:
          resource_group: "{{ rg }}"
          name: "{{ wa_plan }}"
          is_linux: true
          sku: S1
          number_of_worker: 1
        frameworks:
          - name: python
            version: "3.7"
            settings:
              java_container: tomcat
              java_container_version: "8.5"
